version: '3'

services:
  control:
    container_name: control_n
    build:
      context: ./services/control
      dockerfile: Dockerfile
    ports:
      - "22:22"
    networks:
      - ansible_net
    volumes:
      - type: bind
        source: ./effective_ansible
        target: /root/effective_ansible
      - type: bind
        source: ./.ansible.cfg
        target: /root/.ansible.cfg
    # command: tail -f /dev/null # 終了させないためのコマンド
    # depends_on:
    #   - target1
  target1:
    container_name: target1_n
    build:
      context: ./services/target
      dockerfile: Dockerfile
    networks:
      ansible_net:
        ipv4_address: 10.254.249.12
    # command: tail -f /dev/null # 終了させないためのコマンド

    # volumes:

networks:
  ansible_net:
    ipam:
      driver: default
      config:
        - subnet: 10.254.249.0/24
