- name: Setup web server and db server
  hosts:
    - devservers
  tasks:
    - name: Install the latest version of nginx
      command: amazon-linux-extras install nginx1 -y
    - name: Start nginx service
      service:
        name: nginx
        state: started
    - name: Install PostgreSQL
      yum:
        name: postgresql-server
        state: latest
    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started